### ISSUE TITLE
Front-end Roadmap (Web Console)

### ISSUE THREAD

**Issue by yyfearth** [masonwan/marxo#34]
## Web Console

Layout
- [x] Console Layout

User
- [x] Sign-in
- [x] User Profile

Notification
- [x] Notification List
- [x] Notification Manager
- [x] Notification Viewer

Home Screen
- [x] Project Overview

Project
- [x] Project Manager
- [x] Project Editor
- [x] Project Viewer

Workflow
- [x] Workflow  Editor
- [x] Workflow  Manager

Event
- [x] Event Calendar
- [x] Event Editor
- [x] Event Manager

Content
- [x] Content Editor
- [x] Content Manager

Report
- [x] Report Manager
- [x] Results
- [x] Charts

Config
- [x] Tenant Profile
- [x] Facebook Service Connector
- [ ] Twitter Service Connector
- [ ] Email Service Connector
- [x] User Manager
- [x] User Editor

[GDoc](https://docs.google.com/spreadsheet/ccc?key=0ArRXOAfkh0vIdDZ4UEpiMV9VVGlRdVI4S1JZUFQ4Y3c&usp=sharing)
